### ISSUE TITLE
mailway/mailway-local web interface

### ISSUE THREAD

**Issue by rlburkey** [mailway-app/dockerfiles#1]
Good Afternoon!  I'm trying to run the local Mailway docker image and it appears to be running, however I cannot browse to the web address.  It looks like it's auto-fowarding from http to https, but then a page not found error occurs.  Here is the docker command I'm running:

docker run -p 25:25 -p 80:80 -p 443:443 -v /etc/mailway:/etc/mailway -v /var/log/mailway:/var/log/journal -e MW_HOSTNAME=<hostname> -e MW_EMAIL=<email-address> mailway/mailway-local

Any help is appreciated!

**Comment by xtuc** [comment]
Currently the local version doesn't expose a web interface. See https://docs.mailway.app/self-host/local-version to configure the routing.
